name: hello-world
on: 
  workflow_call:
    inputs:
      name:
        description: 'A name passed from the caller workflow'
        required: true
        type: string

      greeting:
        description: 'A greeting passed from the caller workflow'
        required: true
        type: string
      
      ending:
        type: string

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "${{ inputs.greeting }} ${{ inputs.name }}!"