name: Manual | GitHub Actions Demo

on:
  workflow_dispatch:   

jobs:
  gitHub-actions-demo:
    name: Hello GitHub Actions Demo
    uses: cmart1997/sre-toolbox/.github/workflows/workflow-dispatch-called.yml@main
    
